### ISSUE TITLE
查询错误

### ISSUE THREAD

**Issue by jiaojie1989** [protream/tickets#10]
有个编码的错误，环境ubuntu server 16.04, python 2.7.11
```
Traceback (most recent call last):
  File "/usr/local/bin/tickets", line 9, in <module>
    load_entry_point('tickets==0.2.3', 'console_scripts', 'tickets')()
  File "/usr/local/lib/python2.7/dist-packages/tickets/core.py", line 92, in cli
    q.query().pretty_print()
  File "/usr/local/lib/python2.7/dist-packages/tickets/trains.py", line 122, in pretty_print
    for train in self.trains:
  File "/usr/local/lib/python2.7/dist-packages/tickets/trains.py", line 83, in trains
    colored.green(row.get('from_station_name')),
  File "/usr/local/lib/python2.7/dist-packages/tickets/utils.py", line 134, in green
    return self.color_str('GREEN', s)
  File "/usr/local/lib/python2.7/dist-packages/tickets/utils.py", line 127, in color_str
    self.RESET
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```
查询参数
```
tickets 上海虹桥 北京 20160622
```

**Comment by protream** [comment]
@jiaojie1989 新版本不再支持Python2了，建议卸载，用pip3重装

**Comment by jiaojie1989** [comment]
@protream 已经解决，谢谢
