### ISSUE TITLE
cann't run in windows 7 by UnicodeDecodeError

### ISSUE THREAD

**Issue by magic5650** [protream/tickets#11]
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\tickets.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\tickets\core.py", line 92, in cli
    q.query().pretty_print()
  File "C:\Python34\lib\site-packages\tickets\trains.py", line 195, in query
    params = self._build_params()
  File "C:\Python34\lib\site-packages\tickets\trains.py", line 189, in _build_params
    d['from_station'] = self._from_station_telecode
  File "C:\Python34\lib\site-packages\tickets\trains.py", line 158, in _from_station_telecode
    code = self.stations.get(self.from_station)
  File "C:\Python34\lib\site-packages\tickets\trains.py", line 151, in stations
    for line in f.readlines():
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2: illegal multibyte sequence

at last  make it run
https://segmentfault.com/q/1010000002515129/a-1020000002515648

 File "C:\Python34\lib\site-packages\tickets\trains.py", line 151, in stations
with open(filepath, 'rb') as f:

**Comment by lzhr** [comment]
#8  [fix] gbk encode error on windows

**Comment by defhook** [comment]
把你的查询参数贴下看看, stations.dat文件本身是utf-8编码的，报错有点奇怪
