### ISSUE TITLE
运行报错--OS X

### ISSUE THREAD

**Issue by csking119** [protream/tickets#3]
~ tickets -dt 上海 北京 20160615
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/tickets", line 9, in <module>
    load_entry_point('tickets==0.1.7', 'console_scripts', 'tickets')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tickets/core.py", line 34, in <module>
    from _compat import to_unicode
ImportError: No module named '_compat'
```

**Comment by protream** [comment]
你先试试Python2下是否能运行, Python3我只是在开发环境下测试通过了， 包没有发布。我是在Ubuntu下写的，其他平台难免有点问题，欢迎提交Patch:)

**Comment by JoeMinty** [comment]
￼
￼Traceback (most recent call last):
  File "/usr/local/bin/tickets", line 9, in <module>
    load_entry_point('tickets==0.2.2', 'console_scripts', 'tickets')()
  File "/Library/Python/2.7/site-packages/tickets/core.py", line 95, in cli
    q.query().pretty_print()
  File "/Library/Python/2.7/site-packages/tickets/trains.py", line 121, in pretty_print
    for train in self.trains:
  File "/Library/Python/2.7/site-packages/tickets/trains.py", line 82, in trains
    colored.red(row.get('from_station_name')),
  File "/Library/Python/2.7/site-packages/tickets/utils.py", line 130, in red
    return self.color_str('RED', s)
  File "/Library/Python/2.7/site-packages/tickets/utils.py", line 126, in color_str
    colorama.Style.RESET_ALL
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

请问下作者，这是什么问题？

**Comment by protream** [comment]
编码问题， 因为新版本已经不再支持Python2了（不是库，没必要）， 建议卸载重装Python3的版本。
