### ISSUE TITLE
Archlinux python3.5 pip install error

### ISSUE THREAD

**Issue by javaor** [protream/tickets#5]
```python
Collecting tickets
  Using cached tickets-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l11dopr7/tickets/setup.py", line 30, in <module>
        long_description=read('README.rst') + '\n\n' + read('CHANGES'),
      File "/tmp/pip-build-l11dopr7/tickets/setup.py", line 11, in read
        return open(f, encoding='utf-8').read()
      File "/usr/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l11dopr7/tickets/
```

**Comment by protream** [comment]
@javaor 因为对Python的包管理还不是太熟悉，python3 的包还没发布。另外现在在做一个新功能，预计这两天会发布，到时候会一起发布Python3d的包。敬请关注：）

**Comment by javaor** [comment]
嗯，刚使用pip2成功了，加油加油！
![image](https://cloud.githubusercontent.com/assets/8613196/15997774/92c48d74-316a-11e6-821a-645cd9636946.png)
